---
- name: search for java packages on the systems and retun host names that match
  hosts: all
  vars:

  tasks:
          - name: Gather the rpm package facts
            package_facts:
                    manager: auto
          - name: print machines that match packages java
            debug: 
               msg: " {{ packages | select('match', '^java-1.[6-8].0-(sun|oracle)+') | list }} "
          - name: print machines that match packages jre/jdk
            debug:
               msg: " {{ packages | select('match', '^(jre|jdk)')| list }} "

                    
